
const colombia = [];
colombia.push({
    name: "Juanita",
    salary: 1000
});
colombia.push({
    name: "Natalia",
    salary: 500
});
colombia.push({
    name: "Juanita",
    salary: 1000,
});
colombia.push({
    name: "Lucio",
    salary: 800,
});
colombia.push({
    name: "Adrian",
    salary: 250,
});
colombia.push({
    name: "Jose",
    salary: 400,
});
colombia.push({
    name: "Carlos",
    salary: 450
});
colombia.push({
    name: "Jorge",
    salary: 1050,
});
colombia.push({
    name: "Edgar",
    salary: 1200,
});
colombia.push({
    name: "Maria",
    salary: 850,
});
colombia.push({
    name: "Lidia",
    salary: 900,
});
colombia.push({
    name: "Juancarlos",
    salary: 300,
});
colombia.push({
    name: "Thomas",
    salary: 320,
});
colombia.push({
    name: "Tomás",
    salary: 254,
});
colombia.push({
    name: "Lucho",
    salary: 2300,
});
colombia.push({
    name: "Octavio",
    salary: 5000,
});
colombia.push({
    name: "Santiago",
    salary: 1500,
});
colombia.push({
    name: "Luca",
    salary: 650,
});
colombia.push({
    name: "Nacho",
    salary: 600,
});
colombia.push({
    name: "Agustin",
    salary: 1800,
});